#!/bin/bash
if [ $1 ] && [ $2 ]
then
  if [ $2 == 'all' ]
  then
    PS3="select remote path: "
    select files in $files
    do
      filepath=$file
      break
    done
    rsync -zrp $(pwd)/* $filepath~/$flipPath
  elif [[ $2 == 'watch' ]]
    files=$(cat /home/william/bin/data/ssh.txt)
  else
    flipPath=$1
    shift
    rsync -zrp $@ $filepath~/$flipPath
  fi
else
  read -p "Enter files: " localPath
  read -p "Where on flip: " flipPath
  rsync -zrp $localPath $filepath~/$flipPath
fi
